apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: order-command-service
build:
  artifacts:
  - image: order-command-service
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
