apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: order-command-service
build:
  artifacts:
  - image: order-command-service
deploy:
  helm:
    releases:
    - name: order-command-service
      chartPath: helm
      artifactOverrides:
        image.repository: order-command-service