kind: ConfigMap
apiVersion: v1
metadata:
  name: order-command-service
  namespace: default
data:
  config.yaml: |
    topics:
      orderCommands: order-commands
      orderEvents: orders
    postgresqlConfig:
      address: order-command-service-postgresql:5432
      username: postgres
      password: $PG_PASSWORD
      database: postgres
    kafka:
      OrderCommandProducerProperties:
        bootstrap.servers: kafka:9092