kind: ConfigMap
apiVersion: v1
metadata:
  name: order-command-service
  namespace: default
data:
  PG_ADDRESS: "order-command-service-postgresql:5432"
  PG_USERNAME: "postgres"
  PG_DATABASE: "postgres"
  TOPICS_ORDERCOMMANDS: "order-commands"
  TOPICS_ORDEREVENTS: "orders"