apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order-command-service.fullname" . }}
  labels:
    {{- include "order-command-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "order-command-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "order-command-service.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "order-command-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /swagger-ui/
              port: http
          readinessProbe:
            httpGet:
              path: /swagger-ui/
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-command-service-postgresql
                  key: postgresql-password
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: config
          configMap:
            name: order-command-service

