openapi: 3.0.0
info:
  title: "Order-Command API"
  version: "1.0.0"
paths:
  /orders:
    post:
      summary: "Creates a new order"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateOrderResponse'
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Address:
      properties:
        city:
          type: string
        country:
          type: string
        state:
          type: string
        street:
          type: string
        zip_code:
          type: string
      type: object
    CreateOrderRequest:
      properties:
        customer_id:
          type: string
        destination_address:
          $ref: '#/components/schemas/Address'
        expected_delivery_date:
          type: string
        pickup_address:
          $ref: '#/components/schemas/Address'
        pickup_date:
          type: string
        product_id:
          type: string
        quantity:
          format: int64
          type: integer
      type: object
      example:
        product_id: "P02"
        quantity: 101
        customer_id: "GoodManuf"
        expected_delivery_date: "2019-01-10T13:30Z"
        pickup_date: "2019-01-10T13:30Z"
        pickup_address: {"street": "200 1st street", "city": "Shanghai", "country": "China", "state": "", "zip_code": "09430"}
        destination_address: {"street": "500 main street", "city": "San Leonardo", "country": "USA", "state": "CA", "zip_code": "95030"}
    CreateOrderResponse:
      properties:
        customer_id:
          type: string
        destination_address:
          $ref: '#/components/schemas/Address'
        expected_delivery_date:
          type: string
        order_id:
          type: string
        pickup_address:
          $ref: '#/components/schemas/Address'
        pickup_date:
          type: string
        product_id:
          type: string
        quantity:
          format: int64
          type: integer
      type: object
    ErrorResponse:
      properties:
        error:
          type: array
          $ref: '#/components/schemas/Error'
      type: object
    Error:
      properties:
        message:
          type: string
      type: object
